apiVersion: apps/v1
kind: Deployment
metadata:
  name: provenir-robobob-app
  labels:
    app: provenir-robobob-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provenir-robobob-app
  template:
    metadata:
      labels:
        app: provenir-robobob-app
    spec:
      containers:
        - name: spring-boot-container
          image: kapilankam/provenir-robobob-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"