apiVersion: v1
kind: Service
metadata:
  name: provenir-robobob--service
spec:
  selector:
    app: provenir-robobob-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer